name: Build Windows EXE

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install UV (fast package manager)
        run: |
          pip install uv

      - name: Install deps
        run: |
          uv pip install --system -r requirements.txt
          # OR if you use pyproject:
          # uv pip install --system .

      - name: PyInstaller build
        run: |
          pyinstaller build/drive_catalogue.spec

      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: DriveCatalogue-Windows
          path: |
            dist/DriveCatalogue.exe
            dist/DriveCatalogueService.exe
          if-no-files-found: warn

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: DriveCatalogue-Windows
          path: ./bundle

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: bundle/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
